name: Generate images.json

on:
  push:
    paths:
      - 'images/**'    # Alleen triggeren als iets in images/ veranderd

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate images.json
        run: node scripts/generate-images-json.js

      - name: Commit and push changes
        run: |
          git config user.name "squandor"
          git config user.email "s.schins@digitaal-rechercheurs.nl"
          git add images.json
          git diff --cached --quiet || git commit -m "Automatisch images.json bijgewerkt"
          git push
